### ISSUE TITLE
Question about input file of the `tvb_FC` script to calculate the FC matrix

### ISSUE THREAD

**Issue by yilewang** [McIntosh-Lab/tvb-ukbb#163]
Hey everyone, I just have a question about my preprocessing in rfMRI signal. 

The question is about getting time-series data of the rfMRI. I am wondering how should I get my time-series results? When I ran the pipeline, I got error like this:

```bash
/opt/tvb-ukbb/bb_functional_pipeline/tvb_FC: line 25: mri_segstats: command not found
Traceback (most recent call last):
  File "/opt/tvb-ukbb/bb_functional_pipeline/tvb_FC_compute", line 78, in <module>
    main()
  File "/opt/tvb-ukbb/bb_functional_pipeline/tvb_FC_compute", line 50, in main
    TS_old = np.loadtxt(ts_rois)
  File "/opt/tvb-pipeline/software/env/lib/python3.7/site-packages/numpy/lib/npyio.py", line 981, in loadtxt
    fh = np.lib._datasource.open(fname, 'rt', encoding=encoding)
  File "/opt/tvb-pipeline/software/env/lib/python3.7/site-packages/numpy/lib/_datasource.py", line 269, in open
    return ds.open(path, mode, encoding=encoding, newline=newline)
  File "/opt/tvb-pipeline/software/env/lib/python3.7/site-packages/numpy/lib/_datasource.py", line 623, in open
    raise IOError("%s not found." % path)
OSError: /work/08008/yilewang/ls6/hsam/s123873/fMRI/rfMRI.ica/ts_roied_TVBSchaeferTian420.txt not found.
```
https://github.com/yilewang/tvb-ukbb/blob/ADNI3/bb_functional_pipeline/tvb_FC#L14 

After running the pipeline, I didn't generate the `ts_roied.txt` file in my `rfMRI.ica` folder... Does it come with `FIX`? I got error in `FIX` process too but I am not sure if this file is part of the `FIX` output..  

However, I tried to look around the `bb_pipeline_func` but I didn't find a script or function whose output is `ts_roi*`... Could you please help me on it? Thanks!

I am using `ADNI3` branch with singularity container and `TACC` HPC system, ROCKY Linux with SLURM to run my job, just FYI.

**Comment by yilewang** [comment]
Problem solved! It looks like my `freesurfer` path is wrong so it caused the func pipeline issues. However, I still have `ANTs` dependencies issues right now. In the `TVB-UKBB` singularity container, the glibc version is 2.27. However, the ANTs may require glibc version higher than 2.28 to run it... A possible solution is to install another version of the glibc in the container. I will work on it but now I will close this issue

**Comment by noahfl** [comment]
Hey Yile, which version of `ANTS` are you running and which `glibc` does it require? I can look at putting it in the container. I'm also looking at putting everything, including `ANTS`, Free/FastSurfer, and `AFNI` into the container to fully encapsulate all dependencies. This will be a little more complicated though since the container will be too large to upload to Singularity's container repository.

**Comment by noahfl** [comment]
Oh nice! Would you mind sharing the container recipe you have whenever you get the chance? I'd love to take a look and see what you've added.
