### ISSUE TITLE
Diffusion data acquired in the reverse phase encode direction

### ISSUE THREAD

**Issue by hellenmir** [McIntosh-Lab/tvb-ukbb#179]
Thanks a lot for this great resource!

Do you have any implementations for running the current diffusion pipeline on data that has both AP and PA directions?

**Comment by shen4brains** [comment]
Hi @hellenmir. Thanks for checking out our pipeline. There is a related question in our discussion board [here](https://github.com/McIntosh-Lab/tvb-ukbb/discussions/177), and my answer to your question would be the same as I posted there. Happy to continue this over on the discussion board if you have any further questions.
