### ISSUE TITLE
init_vars

### ISSUE THREAD

**Issue by Bea9619** [McIntosh-Lab/tvb-ukbb#190]
Dear all,
I'm trying to run your singularity container for UK biobank MRI data preprocessing. I downloaded the container and followed the instructions to modify init_vars before running the pipeline for a single subject. However, initializing the environment variables, I got the following error:

_/home/psicobiologia/ANALISI/prova/container_tvb/tvb-ukbb/init_vars: line 62: /FreeSurferEnv.sh: No such file or directory_

Line 62 of init_vars: "source $EBROOTFREESURFER/FreeSurferEnv.sh" where EBROOTFREESURFER is not defined anywhere in the script. 
So, trying commenting all the Freesurfer-related lines, I got another error for line 126

_./init_vars: line 126: activate: No such file or directory_

I'm wondering if the paths to the environmental variables have to be the ones on the local PC or if they are already defined in the singularity container.
Thanks in advance

Beatrice

**Comment by shen4brains** [comment]
Hi Beatrice,

Freesurfer, AFNI and ANTS are dependencies that are not currently in the container. Try pointing `init_vars` to Freesurfer ([and the other dependencies](https://github.com/McIntosh-Lab/tvb-ukbb/wiki/Installing-on-a-General-HPC-System#modify-init_vars)) on your local machine.

-Kelly

**Comment by Bea9619** [comment]
> Hi Beatrice,
> 
> Freesurfer, AFNI and ANTS are dependencies that are not currently in the container. Try pointing `init_vars` to Freesurfer ([and the other dependencies](https://github.com/McIntosh-Lab/tvb-ukbb/wiki/Installing-on-a-General-HPC-System#modify-init_vars)) on your local machine.
> 
> -Kelly

Hi Kelly, many thanks for your prompt reply. I tried as you suggested, so I changed FREESURFER_HOME path with my local one but now this is the error, where seems that the container cannot see files or folders outside them:

~/tvb-ukbb/init_vars: line 63: /usr/local/freesurfer/SetUpFreeSurfer.sh: No such file or directory

Have you any other ideas to fix this? 
Thanks

Beatrice

**Comment by shen4brains** [comment]
Hi Beatrice,

Has the location of your local Freesurfer directory been "bound" for the container to find? This is done using the `-B` flag in the command to launch the container.

If you still need support for this, can you please post to our [Discussions](https://github.com/McIntosh-Lab/tvb-ukbb/discussions) board?

Thanks,
Kelly
